import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  id: {
    // App.jsx (Sidebar)
    'menu.dashboard': 'Beranda',
    'menu.transactions': 'Riwayat Transaksi',
    'menu.savings': 'Target Tabungan',
    'menu.statistics': 'Statistik & Analisis',
    'menu.debts': 'Hutang & Piutang',
    'menu.calendar': 'Kalender Keuangan',
    'menu.categories': 'Kategori & Limit',
    'menu.ai': 'Savora AI Chat',
    'menu.notifications': 'Notifikasi',
    'menu.settings': 'Pengaturan',
    'menu.help': 'Pusat Bantuan',
    'menu.logout': 'Keluar Akun',
    'header.title.dashboard': 'Selamat Datang di Savora!',
    'header.title.transactions': 'Riwayat Transaksi',
    'header.title.savings': 'Target Tabungan',
    'header.title.statistics': 'Statistik & Analisis',
    'header.title.debts': 'Hutang & Piutang',
    'header.title.calendar': 'Kalender Keuangan',
    'header.title.categories': 'Kategori & Limit',
    'header.title.ai': 'Savora AI Advisor',
    'header.title.settings': 'Pengaturan',
    'header.title.notifications': 'Pusat Notifikasi',
    'header.title.help': 'Savora Academy & Bantuan',
    'header.subtitle': 'Pantau dan kelola aset masa depan Anda secara instan.',
    'header.subtitle.help': 'Hubungi administrator Savora atau pelajari tutorial fitur harian.',
    'btn.lang': 'Bahasa: Indonesia',
    'btn.add_tx': 'Catat Transaksi',

    // Help.jsx
    'help.title': 'Pusat Bantuan Savora',
    'help.desc': 'Panduan cepat penggunaan aplikasi Savora Finance',
    'help.faq.title': 'FAQ (Tanya Jawab)',
    'help.guide.title': 'Panduan & Cara Penggunaan Fitur Savora',
    'help.support.title': 'Hubungi Tim Dukungan',
    'help.support.desc': 'Butuh bantuan teknis atau ada kendala?',
    'help.support.track': 'Lacak Tiket',
    'help.support.name': 'Nama Lengkap',
    'help.support.email': 'Email Aktif',
    'help.support.problem': 'Deskripsi Kendala',
    'help.support.send': 'Kirim Tiket Bantuan',
    'help.guide.ocr': 'Scan Nota & OCR AI',
    'help.guide.read': 'Baca',

    // Dashboard.jsx
    'dashboard.total_dana': 'Total Dana Savora',
    'dashboard.pemasukan': 'Pemasukan',
    'dashboard.pengeluaran': 'Pengeluaran',
    'dashboard.akun_saldo': 'Akun & Saldo',
    'dashboard.kelola_akun': 'Kelola Akun',
    'dashboard.kelola_kategori': 'Kelola Kategori',
    'dashboard.semua_rekening': 'Semua Rekening',
    'dashboard.transaksi_terakhir': 'Transaksi Terakhir',
    'dashboard.aktivitas_terbaru': 'Aktivitas keuangan terbaru Anda',
    'dashboard.lihat_semua': 'Lihat Semua',
    
    // Settings.jsx
    'settings.title': 'Pengaturan Savora',
    'settings.desc': 'Kelola preferensi dan keamanan data Anda.',
    'settings.cloud': 'Konektivitas & Sistem Cloud',
    'settings.uji': 'Uji Koneksi Supabase',
    'settings.uji_desc': 'Pastikan Anda terhubung ke database realtime.',
    'settings.data': 'Manajemen Data',
    'settings.arsip': 'Arsip Otomatis Data Lama',
    'settings.arsip_desc': 'Unduh riwayat transaksi lawas ke Excel (CSV) dan hapus dari database untuk performa aplikasi yang lebih ringan dan cepat.',
    'settings.reset': 'Reset Total Database (Factory Reset)',
    'settings.reset_desc': 'Kembalikan seluruh basis data ke setelan awal. Menghapus semua riwayat transaksi, rekening, tabungan, dan UI statis.',
    
    // New strings for Backup/Restore/Profile
    'settings.profile': 'Profil Pengguna',
    'settings.profile_desc': 'Ubah nama tampilan Anda di aplikasi.',
    'settings.profile_name_label': 'Nama Tampilan',
    'settings.profile_save': 'Simpan Profil',
    'settings.profile_save_success': 'Profil berhasil diperbarui!',
    'settings.backup_restore': 'Backup & Restore Data',
    'settings.backup_restore_desc': 'Salin atau pulihkan data Anda dalam format JSON. Berbeda dengan arsip, data Anda tidak akan dihapus.',
    'settings.btn_backup': 'Salin Backup ke Clipboard',
    'settings.backup_success': 'Data berhasil disalin ke Clipboard!',
    'settings.backup_fail': 'Gagal membuat backup',
    'settings.restore_ph': 'Tempel (Paste) JSON backup Anda di sini...',
    'settings.btn_paste': 'Tempel dari Clipboard',
    'settings.btn_restore': 'Pulihkan Data',
    'settings.restore_success': 'Data berhasil dipulihkan!',
    'settings.restore_fail': 'Format JSON tidak valid atau rusak.',
    'settings.about_savora': 'Tentang Savora AI',
    'settings.about_desc': 'Aplikasi pencatatan keuangan cerdas dengan integrasi AI (LLaMA 3) untuk analisis dan kemudahan Anda.',
    'settings.about_version': 'Versi 1.0.0 (AI Edition)',
    'settings.about_dev': 'Dikembangkan oleh Anda',

    // Transactions.jsx
    'tx.title': 'Riwayat Transaksi Lengkap',
    'tx.subtitle': 'Seluruh rekam jejak aktivitas pengeluaran dan pemasukan',
    'tx.export': 'Ekspor ke CSV (Excel)',
    'tx.search_desc': 'Cari Deskripsi',
    'tx.search_placeholder': 'Cari...',
    'tx.type': 'Tipe',
    'tx.type_all': 'Semua Tipe',
    'tx.type_income': 'Pemasukan',
    'tx.type_expense': 'Pengeluaran',
    'tx.type_transfer': 'Transfer Kas',
    'tx.category': 'Kategori',
    'tx.category_all': 'Semua Kategori',
    'tx.account': 'Akun / Rekening',
    'tx.account_all': 'Semua Akun',
    'tx.sort': 'Urutkan',
    'tx.sort_newest': 'Terbaru',
    'tx.sort_oldest': 'Terlama',
    'tx.sort_highest': 'Jumlah Tertinggi',
    'tx.sort_lowest': 'Jumlah Terendah',
    'tx.col_date': 'Tanggal',
    'tx.col_type': 'Tipe',
    'tx.col_category': 'Kategori',
    'tx.col_desc': 'Deskripsi / Catatan',
    'tx.col_amount': 'Jumlah',
    'tx.col_action': 'Aksi',
    'tx.loading': 'Memuat data...',
    'tx.not_found': 'Data transaksi tidak ditemukan.',
    'tx.delete_confirm': 'Apakah Anda yakin ingin menghapus transaksi ini?',
    'tx.delete_success': 'Transaksi berhasil dihapus!',
    'tx.delete_fail': 'Gagal menghapus: ',
    'tx.export_success': 'Berhasil mengekspor data ke CSV',
    'tx.delete': 'Hapus',

    // Savings.jsx
    'savings.delete_confirm': 'Apakah Anda yakin ingin menghapus target tabungan ini secara permanen?',
    'savings.delete_success': 'Tabungan berhasil dihapus!',
    'savings.delete_fail': 'Gagal menghapus tabungan: ',
    'savings.title': 'Wadah Tabungan Savora',
    'savings.subtitle': 'Atur dan alokasikan dana simpanan secara rapi',
    'savings.filter_all': 'Semua',
    'savings.add_title': 'Buat Target Baru',
    'savings.add_subtitle': 'Alokasikan anggaran khusus impian Anda',
    'savings.btn_deposit': 'Setor',
    'savings.deadline': 'Deadline',
    'savings.schedule_auto': 'Auto',
    'savings.schedule_manual': 'Manual',

    // Debts.jsx
    'debts.load_fail': 'Gagal memuat data hutang piutang',
    'debts.add_success': 'Data berhasil ditambahkan',
    'debts.add_fail': 'Gagal menambah data: ',
    'debts.delete_confirm': 'Yakin ingin menghapus data ini?',
    'debts.delete_success': 'Data berhasil dihapus',
    'debts.delete_fail': 'Gagal menghapus data',
    'debts.pay_success': 'Pembayaran berhasil dicatat',
    'debts.pay_fail': 'Gagal mencatat pembayaran',
    'debts.title': 'Catatan Hutang & Piutang',
    'debts.subtitle': 'Pantau kewajiban dan piutang Anda',
    'debts.btn_add': 'Tambah',
    'debts.tab_active': 'Catatan Aktif',
    'debts.tab_history': 'Riwayat Pembayaran',
    'debts.empty_active_title': 'Belum ada catatan',
    'debts.empty_active_desc': 'Mulai catat hutang atau piutang baru',
    'debts.empty_history_title': 'Belum ada riwayat pembayaran',
    'debts.empty_history_desc': 'Pembayaran hutang/piutang akan muncul di sini',
    'debts.status_lunas': 'LUNAS',
    'debts.status_aktif': 'AKTIF',
    'debts.no_desc': 'Tidak ada keterangan',
    'debts.total': 'Total:',
    'debts.paid': 'Terbayar:',
    'debts.remaining': 'Sisa:',
    'debts.btn_pay': 'Bayar',
    'debts.history_pay_debt': 'Pembayaran Hutang:',
    'debts.history_pay_debt': 'Pembayaran Hutang:',
    'debts.history_pay_receive': 'Pembayaran Piutang:',
    'debts.modal_add_title': 'Catat Baru',
    'debts.modal_type': 'Tipe',
    'debts.type_debt': 'Hutang',
    'debts.type_receive': 'Piutang',
    'debts.modal_name': 'Nama Pihak (Siapa?)',
    'debts.modal_name_ph': 'Contoh: Budi',
    'debts.modal_amount': 'Jumlah (Rp)',
    'debts.modal_amount_ph': '50000',
    'debts.modal_desc': 'Keterangan (Opsional)',
    'debts.modal_desc_ph': 'Uang makan',
    'debts.modal_deadline': 'Tenggat Waktu (Opsional)',
    'debts.modal_btn_save': 'Simpan Catatan',
    'debts.modal_pay_title': 'Catat Pembayaran',
    'debts.modal_pay_for': 'Membayar untuk:',
    'debts.modal_pay_remain': 'Sisa tagihan: ',
    'debts.modal_pay_amount': 'Jumlah Bayar (Rp)',
    'debts.modal_pay_acc': 'Pilih Rekening Kas',
    'debts.modal_pay_note_dec': 'Saldo rekening ini akan otomatis berkurang.',
    'debts.modal_pay_note_inc': 'Saldo rekening ini akan otomatis bertambah.',
    'debts.modal_btn_pay': 'Simpan Pembayaran',

    // Categories.jsx
    'cat.add_success': 'Kategori berhasil ditambahkan!',
    'cat.add_fail': 'Gagal menyimpan: ',
    'cat.delete_confirm': 'Hapus kategori ini?',
    'cat.delete_success': 'Kategori berhasil dihapus.',
    'cat.delete_fail': 'Gagal menghapus kategori: ',
    'cat.add_title': 'Tambah Kategori Baru',
    'cat.add_subtitle': 'Kelompokkan pengeluaran Anda sesuai kebutuhan',
    'cat.label_name': 'Nama Kategori',
    'cat.placeholder_name': 'Contoh: Belanja Bulanan',
    'cat.label_type': 'Tipe Kategori',
    'cat.label_limit': 'Batas Anggaran Bulanan',
    'cat.label_optional': '(Opsional)',
    'cat.placeholder_limit': 'Contoh: 1500000',
    'cat.btn_save': 'Simpan Kategori',
    'cat.btn_saving': 'Menyimpan...',
    'cat.list_title': 'Daftar Kategori & Kontrol Limit',
    'cat.list_subtitle': 'Atur batas anggaran belanja bulanan agar tidak overbudget.',
    'cat.col_name': 'Nama Kategori',
    'cat.col_type': 'Tipe',
    'cat.col_limit': 'Limit Anggaran',
    'cat.col_action': 'Aksi',
    'cat.empty': 'Belum ada kategori kustom.',

    // Statistics.jsx
    'stat.tab_cashflow': 'Aliran Kas',
    'stat.tab_breakdown': 'Porsi Pengeluaran',
    'stat.tab_assets': 'Proporsi Aset',
    'stat.cf_title': 'Statistik Aliran Dana',
    'stat.cf_subtitle': 'Visualisasi aliran masuk & keluar kas bulan ini',
    'stat.cf_income': 'Pemasukan',
    'stat.cf_expense': 'Pengeluaran',
    'stat.loading_chart': 'Memuat grafik...',
    'stat.bd_title': 'Distribusi Kategori',
    'stat.bd_total': 'Total Pengeluaran:',
    'stat.assets_title': 'Proporsi Alokasi Aset',
    'stat.assets_subtitle': 'Distribusi total dana Savora Anda di setiap rekening aktif',
    'stat.assets_empty': 'Saldo aset kosong.',
    'stat.status_title': 'Status Akun Aktif',
    'stat.status_monitored': 'Akun yang Dipantau',
    'stat.status_all': 'Semua Akun',
    'stat.status_total': 'Total Dana',
    'stat.health_title': 'Savora Health Index',
    'stat.health_good': 'Bagus! Cashflow Anda positif. Pertahankan untuk masa depan yang aman.',
    'stat.health_bad': 'Hati-hati! Pengeluaran Anda melebihi aset. Segera tinjau ulang anggaran harian.',

    // Calendar.jsx
    'cal.save_fail': 'Gagal menyimpan catatan',
    'cal.month_income': 'Pemasukan Bulan Ini',
    'cal.month_expense': 'Pengeluaran Bulan Ini',
    'cal.month_net': 'Net Bersih',
    'cal.sun': 'Min',
    'cal.mon': 'Sen',
    'cal.tue': 'Sel',
    'cal.wed': 'Rab',
    'cal.thu': 'Kam',
    'cal.fri': 'Jum',
    'cal.sat': 'Sab',
    'cal.panel_title': 'Aktivitas Harian',
    'cal.journal': 'Jurnal Keuangan',
    'cal.journal_ph': 'Tulis catatan pengeluaran, ide, atau refleksi finansial hari ini...',
    'cal.budget_limit': 'Limit Anggaran Harian',
    'cal.budget_limit_ph': 'Set limit pengeluaran...',
    'cal.usage': 'Penggunaan',
    'cal.overbudget': 'Overbudget',
    'cal.safe': 'Aman',
    'cal.reminders': 'Pengingat',
    'cal.reminder_ph': 'Tambah pengingat tagihan...',
    'cal.tx_history': 'Riwayat Transaksi Harian',
    'cal.tx_empty': 'Tidak ada transaksi',

    // AiAssistant.jsx
    'ai.consult_welcome': 'Halo! Saya Savora AI. Saya dapat menganalisis keuangan Anda atau memberikan rekomendasi investasi dan tips hemat uang. Silakan ketik pertanyaan Anda! (Contoh: "Bagaimana cara hemat belanja bulanan?")',
    'ai.catat_welcome': 'Mode Catat Instan siap. Sebutkan transaksi Anda seperti "Beli kopi 50 ribu cash", dan saya akan mencatatnya ke buku kas Anda.',
    'ai.clear_confirm': 'Hapus riwayat obrolan untuk mode ini?',
    'ai.consult_cleared': 'Riwayat obrolan konsultasi telah dihapus.',
    'ai.catat_cleared': 'Riwayat obrolan catat instan telah dihapus.',
    'ai.title': 'Savora Financial AI Advisor',
    'ai.status': 'Online & Siap Menjawab',
    'ai.mode_consult': 'Mode Konsultasi',
    'ai.mode_catat': 'Mode Chat Instan',
    'ai.placeholder': 'Ketik pesan Anda di sini...',
    'ai.btn_send': 'Kirim',
    'ai.response_consult': '💡 Terkait pertanyaan Anda "{msg}", saran dari Savora AI: Selalu catat pengeluaran harian dan pastikan tidak melebihi 30% dari sisa gaji bulan ini. (Sistem AI asli sedang dalam integrasi)',
    'ai.response_catat_success': '✅ Sukses! Saya telah mencatat {type} sejumlah {amount} untuk "{desc}" di dompet "{account}".{accMsg}',
    'ai.response_catat_fail': '❌ Gagal mencatat transaksi: {error}',
    'ai.response_catat_unknown': '❓ Maaf, saya tidak mengerti maksud Anda. Coba format yang lebih jelas seperti: "Beli kopi 50 ribu cash" atau "Terima gaji 5 juta BCA".',
    'ai.acc_created': '\n(Akun dompet baru "{account}" telah dibuat otomatis).',

    // Notifications.jsx
    'notif.load_fail': 'Gagal memuat notifikasi',
    'notif.save_fail': 'Gagal menyimpan pengaturan',
    'notif.limit_success': 'Batas saldo berhasil disimpan',
    'notif.limit_fail': 'Gagal menyimpan batas saldo: ',
    'notif.clear_confirm': 'Hapus seluruh riwayat notifikasi?',
    'notif.clear_success': 'Riwayat berhasil dihapus',
    'notif.clear_fail': 'Gagal menghapus riwayat',
    'notif.title': 'Riwayat Notifikasi Finansial',
    'notif.subtitle': 'Rekaman seluruh aktivitas keamanan, limit anggaran, dan tagihan akun Anda',
    'notif.filter_all': 'Semua',
    'notif.filter_unread': 'Belum Dibaca',
    'notif.btn_clear': 'Hapus Riwayat',
    'notif.empty': 'Tidak ada notifikasi untuk ditampilkan.',
    'notif.warn_title': 'Peringatan!',
    'notif.info_title': 'Informasi',
    'notif.btn_transfer': 'Pindahkan Dana',
    'notif.config_title': 'Konfigurasi Pengingat',
    'notif.config_subtitle': 'Sesuaikan batas peringatan Savora',
    'notif.cfg_overbudget': 'Peringatan Overbudget',
    'notif.cfg_overbudget_desc': 'Beri tahu ketika pengeluaran kategori mencapai batas anggaran',
    'notif.cfg_critical': 'Peringatan Saldo Kritis',
    'notif.cfg_critical_desc': 'Beri tahu jika saldo rekening utama Anda menipis',
    'notif.cfg_critical_min': 'Batas Minimum Saldo',
    'notif.cfg_checklist': 'Pengingat Checklist Tagihan',
    'notif.cfg_checklist_desc': 'Beri tahu jika ada agenda harian pending',
    'notif.msg_critical_desc': 'Saldo rekening {account} kamu sekarang di bawah batas aman ({amount}).',
    'notif.msg_checklist_desc': 'Anda memiliki {count} tugas/tagihan yang belum selesai hari ini.',
    'notif.msg_overbudget_desc': 'Pengeluaran untuk kategori {category} bulan ini ({spent}) telah melebihi batas ({limit}).',

    // Dashboard.jsx
    'dashboard.welcome': 'Selamat Datang,',
    'dashboard.user_default': 'Pengguna',
    'dashboard.ocr_start': 'Memulai analisis struk dengan AI...',
    'dashboard.ocr_err_key': 'Groq API Key belum dikonfigurasi di Pengaturan.',
    'dashboard.ocr_err_api': 'Gagal memanggil API Groq',
    'dashboard.ocr_err_format': 'Format respon AI tidak valid',
    'dashboard.ocr_success': 'Berhasil membaca struk!',
    'dashboard.ocr_invalid': 'Tidak menemukan nominal yang valid pada struk.',
    'dashboard.ocr_fail': 'Gagal memproses struk: ',
    'dashboard.ocr_title': 'Savora AI Scan',
    'dashboard.ocr_subtitle': 'Ambil foto struk belanja untuk dicatat otomatis.',
    'dashboard.ocr_title_loading': 'Menganalisis Struk...',
    'dashboard.ocr_subtitle_loading': 'Tesseract.js sedang memproses gambar...',
    'dashboard.btn_scan': 'Scan Struk (OCR)',
    'dashboard.btn_scanning': 'Memindai...',
    'dashboard.tx_empty': 'Belum ada aktivitas transaksi.',

    // Settings - Additional
    'settings.del_confirm': 'Hapus dompet ini? Semua transaksi yang terkait mungkin kehilangan referensi dompet.',
    'settings.del_success': 'Dompet berhasil dihapus.',
    'settings.del_fail': 'Gagal menghapus dompet: ',
    'settings.up_fail': 'Gagal memperbarui pengaturan: ',
    'settings.pin_err': 'PIN harus 4 digit',
    'settings.pin_success': 'PIN Keamanan berhasil disimpan!',
    'settings.pin_fail': 'Gagal menyimpan PIN: ',
    'settings.groq_success': 'Groq API Key berhasil disimpan!',
    'settings.groq_fail': 'Gagal menyimpan Groq API Key: ',
    'settings.reset_warn': 'PERINGATAN KRITIKAL: Seluruh data riwayat, dompet, dan tabungan Anda akan dihapus permanen. Lanjutkan?',
    'settings.reset_success': 'Database telah di-reset ke setelan pabrik!',
    'settings.reset_fail': 'Gagal mereset database: ',
    'settings.archive_empty': 'Sistem sangat optimal! Tidak ada transaksi lama (lebih dari 30 hari) yang perlu diarsip saat ini.',
    'settings.archive_success': 'Berhasil mengarsip dan mengunduh transaksi lama! Database sekarang lebih ringan.',
    'settings.archive_fail': 'Gagal mengarsip data: ',
    'settings.btn_connect_bank': 'Hubungkan Rekening',
    'settings.lbl_connected': 'Terhubung',
    'settings.btn_run_archive': 'Jalankan Arsip',
    'settings.btn_run_reset': 'Jalankan Reset',
    'settings.lbl_fin_config': 'Konfigurasi Finansial',
    'settings.lbl_def_acc': 'Akun Rekening Default',
    'settings.desc_def_acc': 'Rekening utama yang otomatis langsung terpilih saat membuat transaksi baru.',
    'settings.lbl_acc_list': 'Daftar Rekening & Dompet',
    'settings.desc_acc_list': 'Kelola daftar dompet, rekening bank, atau e-wallet yang Anda miliki.',
    'settings.btn_add_acc': 'Tambah Dompet',
    'settings.lbl_currency': 'Format Mata Uang',
    'settings.desc_currency': 'Pilih format tampilan mata uang antara Rupiah (IDR) atau Dollar (USD).',
    'settings.lbl_security': 'Keamanan & Fitur Aplikasi',
    'settings.lbl_pin_lock': 'Kunci Aplikasi dengan PIN',
    'settings.desc_pin_lock': 'Memerlukan verifikasi kode PIN 4 digit untuk membuka Savora saat dimuat.',
    'settings.lbl_change_pin': 'Ganti Kode PIN Kunci',
    'settings.desc_change_pin': 'Ubah kode sandi 4 digit untuk akses perlindungan keamanan internal harian Anda.',
    'settings.lbl_ai_integ': 'Integrasi AI (Groq API Key)',
    'settings.desc_ai_integ': 'Masukkan Groq API Key Anda (gsk_...) untuk mengaktifkan Savora AI Scan (OCR).',
    'settings.lbl_haptic': 'Umpan Balik Taktil (Getar)',
    'settings.desc_haptic': 'Aktifkan efek getar taktil halus saat Anda menekan tombol Savora harian.',
    'settings.btn_save': 'Simpan',
    'settings.select': '-- Pilih --',
    'settings.edit_wallet': 'Edit Dompet',
    'settings.del_wallet': 'Hapus Dompet',

    // Help - Additional
    'help.faq.1.q': 'Apakah data saya aman di Savora?',
    'help.faq.1.a': 'Sangat aman! Seluruh data transaksi Savora tersimpan langsung di dalam Cloud pribadi menggunakan Row Level Security milik Supabase.',
    'help.faq.2.q': 'Bagaimana jika lupa PIN keamanan?',
    'help.faq.2.a': 'Anda dapat melakukan reset PIN melalui menu Pengaturan, atau membersihkan data lokal aplikasi jika PIN terkunci sepenuhnya.',
    'help.guide.ai': 'Perintah Savora AI Chat',
    'help.guide.savings': 'Rencana Saku Tabungan',
    'help.guide.limits': 'Batas Anggaran & Limit',
    'help.support.track_msg': 'Sistem pelacakan tiket (Zendesk) sedang dalam pemeliharaan (Simulasi MVP).',
    'help.support.send_msg': 'Tiket bantuan terkirim! (Simulasi)',
    'help.modal.ocr.title': 'Panduan Scan Struk & OCR',
    'help.modal.ocr.tag': 'SAVORA PREMIUM ACADEMY',
    'help.modal.ocr.desc': 'Fitur Scan Nota AI Savora memungkinkan Anda merekam bukti pengeluaran fisik dalam hitungan detik.',
    'help.modal.how_to': 'CARA MENGGUNAKAN:',
    'help.modal.ocr.step1': 'Klik tombol "Scan Struk (OCR)" di beranda.',
    'help.modal.ocr.step2': 'Gunakan file struk belanja.',
    'help.modal.ocr.step3': 'Savora AI akan mengekstrak nominal belanja secara otomatis.',
    'help.modal.ocr.tips': 'Tips: Pastikan gambar jelas.',
    'help.modal.ai.title': 'Perintah Savora AI Chat',
    'help.modal.ai.desc': 'Savora AI Chat dirancang sebagai asisten finansial cerdas Anda yang berbasis NLP (Natural Language Processing).',
    'help.modal.ai.step1': 'Buka menu "Savora AI Chat" dari sidebar.',
    'help.modal.ai.step2': 'Ketikkan pesan secara kasual, misalnya: "Bantu saya atur gaji 5 juta bulan ini".',
    'help.modal.ai.step3': 'Anda juga bisa mencatat, misal: "Saya beli kopi 25rb pakai GOPAY".',
    'help.modal.ai.tips': 'Tips: Semakin sering bertanya, semakin AI mengenali pola Anda.',
    'help.modal.savings.title': 'Rencana Saku Tabungan',
    'help.modal.savings.desc': 'Fitur Saku Tabungan (Savings Pocket) membantu mengalokasikan uang Anda dari pengeluaran harian.',
    'help.modal.savings.step1': 'Buka menu "Target Tabungan" dan klik Buat Target.',
    'help.modal.savings.step2': 'Tentukan Nama Impian, Nominal, dan Tenggat Waktu.',
    'help.modal.savings.step3': 'Pindahkan saldo dari Akun Utama ke Saku Tabungan.',
    'help.modal.savings.tips': 'Tips: Saldo di Tabungan otomatis tidak terlihat di grafik Pengeluaran Bulanan agar tidak rancu.',
    'help.modal.limits.title': 'Batas Anggaran & Limit',
    'help.modal.limits.desc': 'Batas Anggaran bertindak sebagai rem pengeluaran Anda.',
    'help.modal.limits.step1': 'Buka menu "Kategori & Limit".',
    'help.modal.limits.step2': 'Tambahkan kategori dan tentukan batas bulanan.',
    'help.modal.limits.step3': 'Ketika transaksi menembus batas, sistem notifikasi memberi peringatan.',
    'help.modal.limits.tips': 'Tips: Biasakan mengalokasikan 20% penghasilan untuk menabung.',
    'help.modal.btn_understand': 'Saya Mengerti',
    'help.modal.btn_close': 'Tutup',
    'help.btn.ocr': 'Mulai Scan Sekarang',
    'help.btn.ai': 'Mulai Chat Savora AI',
    'help.btn.savings': 'Buat Target Tabungan',
    'help.btn.limits': 'Atur Limit Sekarang',

    // Modals
    'modal_tx.title_new': 'Catat Transaksi Baru',
    'modal_tx.type_label': 'Tipe Transaksi',
    'modal_tx.income': 'Pemasukan',
    'modal_tx.expense': 'Pengeluaran',
    'modal_tx.saving': 'Tabungan',
    'modal_tx.transfer': 'Transfer Kas',
    'modal_tx.amount_label': 'Jumlah Nominal',
    'modal_tx.amount_ph': 'Contoh: 50000',
    'modal_tx.category_label': 'Pilih Kategori',
    'modal_tx.category_other': 'Lainnya',
    'modal_tx.desc_label': 'Deskripsi / Catatan Singkat',
    'modal_tx.desc_ph': 'Contoh: Makan Siang di Warteg',
    'modal_tx.source_account': 'Akun Sumber (Dari)',
    'modal_tx.account': 'Akun / Metode Pembayaran',
    'modal_tx.dest_account': 'Akun Tujuan (Ke)',
    'modal_tx.btn_saving': 'Mencatat...',
    'modal_tx.btn_save': 'Catat Transaksi Sekarang',
    'modal_tx.success': 'Transaksi berhasil ditambahkan!',
    'modal_tx.fail': 'Gagal menyimpan transaksi: ',

    'modal_acc.title_new': 'Tambah Dompet / Rekening',
    'modal_acc.name_label': 'Nama Dompet (cth: Dompet Istri)',
    'modal_acc.name_ph': 'Masukkan nama dompet...',
    'modal_acc.type_label': 'Tipe Akun',
    'modal_acc.type_cash': 'Cash / Uang Tunai',
    'modal_acc.type_bank': 'Rekening Bank',
    'modal_acc.type_ewallet': 'E-Wallet (Gopay, OVO)',
    'modal_acc.balance_label': 'Saldo Awal (Opsional)',
    'modal_acc.btn_saving': 'Menyimpan...',
    'modal_acc.btn_save': 'Simpan Dompet',
    'modal_acc.success': 'Dompet berhasil ditambahkan!',
    'modal_acc.fail': 'Gagal menambahkan dompet: ',
    'modal_acc.title_edit': 'Edit Dompet',
    'modal_acc.name_new_label': 'Nama Dompet Baru',
    'modal_acc.note': 'Catatan: Saldo tidak dapat diubah dari sini. Silakan buat Transaksi Penyesuaian untuk mengubah saldo.',
    'modal_acc.btn_save_edit': 'Simpan Perubahan',
    'modal_acc.success_edit': 'Dompet berhasil diperbarui!',
    'modal_acc.fail_edit': 'Gagal memperbarui dompet: ',

    'modal_sg.title': 'Buat Rencana Tabungan',
    'modal_sg.name_label': 'Nama Impian / Target',
    'modal_sg.name_ph': 'Contoh: DP Rumah Impian, Laptop Baru',
    'modal_sg.amount_label': 'Target Nominal',
    'modal_sg.amount_ph': 'Contoh: 15000000',
    'modal_sg.category_label': 'Kategori Tabungan (Saku)',
    'modal_sg.cat_personal': 'Personal',
    'modal_sg.cat_mutual': 'Mutual',
    'modal_sg.cat_family': 'Family',
    'modal_sg.cat_custom': '+ Tulis Kategori Kustom',
    'modal_sg.cat_custom_ph': 'Kategori Baru',
    'modal_sg.init_balance_label': 'Simpanan Awal',
    'modal_sg.deadline_label': 'Tenggat Waktu Target',
    'modal_sg.schedule_label': 'Jadwal Setoran Rutin',
    'modal_sg.sch_manual': '🔄 Bebas (Manual)',
    'modal_sg.sch_first_day': '🌅 Setiap Awal Bulan (Tgl 1)',
    'modal_sg.sch_last_day': '🌇 Setiap Akhir Bulan',
    'modal_sg.sch_specific_date': '📅 Tanggal Spesifik (Bulanan)',
    'modal_sg.date_label': 'Tanggal Setoran Bulanan (1-28)',
    'modal_sg.date_ph': 'Contoh: 10',
    'modal_sg.btn_saving': 'Menyimpan...',
    'modal_sg.btn_save': 'Simpan Target Impian',
    'modal_sg.success': 'Target tabungan berhasil dibuat!',
    'modal_sg.fail': 'Gagal menyimpan target tabungan: ',

    'modal_contrib.title': 'Setor ke Tabungan',
    'modal_contrib.target_lbl': 'Target:',
    'modal_contrib.amount_lbl': 'Nominal Setoran',
    'modal_contrib.amount_ph': 'Contoh: 1000000',
    'modal_contrib.source_lbl': 'Pilih Sumber Dana',
    'modal_contrib.btn_saving': 'Menyetor...',
    'modal_contrib.btn_save': 'Konfirmasi Setoran',
    'modal_contrib.note': '*Fitur autodebet (tarik otomatis setiap tanggal tertentu) sedang dalam tahap pengembangan Savora.',
    'modal_contrib.success': 'Setoran ke tabungan berhasil!',
    'modal_contrib.fail': 'Gagal menyetor dana: ',
    'modal_contrib.insufficient_pt1': 'Saldo di dompet ',
    'modal_contrib.insufficient_pt2': ' tidak mencukupi (Sisa: Rp ',

    'modal_bank.title_select': 'Pilih Bank',
    'modal_bank.title_login': 'Login',
    'modal_bank.title_connect': 'Menghubungkan...',
    'modal_bank.desc_select': 'Pilih bank yang ingin Anda hubungkan dengan Savora (Open Banking API).',
    'modal_bank.desc_secure': 'Koneksi diamankan dengan enkripsi End-to-End. Savora tidak menyimpan kredensial bank Anda.',
    'modal_bank.user_lbl': 'Username / User ID',
    'modal_bank.user_ph': 'Masukkan User ID Bank',
    'modal_bank.pass_lbl': 'Password / PIN',
    'modal_bank.pass_ph': '••••••••',
    'modal_bank.btn_back': 'Kembali',
    'modal_bank.btn_connect': 'Hubungkan',
    'modal_bank.sync_title': 'Sinkronisasi Data',
    'modal_bank.sync_desc_pt1': 'Sedang menghubungkan Savora dengan ',
    'modal_bank.sync_desc_pt2': ' melalui API aman...',
    'modal_bank.success_pt1': 'Berhasil terhubung dengan ',
    'modal_bank.success_pt2': '! Rekening telah disinkronkan.',
    'modal_bank.fail': 'Gagal menghubungkan ke ',

    'modal_notif.loading': 'Memuat...',
    'modal_notif.empty': 'Tidak ada notifikasi aktif.',
    'modal_notif.warn_title': 'Peringatan!',
    'modal_notif.info_title': 'Informasi',
    'modal_notif.title': 'Pusat Notifikasi',
    'modal_notif.subtitle': 'Peringatan Keuangan Aktif',
    'modal_notif.btn_all': 'Lihat Semua & Konfigurasi',
    'modal_notif.btn_close': 'Tutup',
  },
  en: {
    // App.jsx (Sidebar)
    'menu.dashboard': 'Dashboard',
    'menu.transactions': 'Transactions',
    'menu.savings': 'Savings Pocket',
    'menu.statistics': 'Statistics & Analysis',
    'menu.debts': 'Debts & Receivables',
    'menu.calendar': 'Financial Calendar',
    'menu.categories': 'Categories & Limits',
    'menu.ai': 'Savora AI Chat',
    'menu.notifications': 'Notifications',
    'menu.settings': 'Settings',
    'menu.help': 'Help Center',
    'menu.logout': 'Sign Out',
    'header.title.dashboard': 'Welcome to Savora!',
    'header.title.transactions': 'Transaction History',
    'header.title.savings': 'Savings Target',
    'header.title.statistics': 'Statistics & Analysis',
    'header.title.debts': 'Debts & Receivables',
    'header.title.calendar': 'Financial Calendar',
    'header.title.categories': 'Categories & Limits',
    'header.title.ai': 'Savora AI Advisor',
    'header.title.settings': 'Settings',
    'header.title.notifications': 'Notification Center',
    'header.title.help': 'Savora Academy & Help',
    'header.subtitle': 'Monitor and manage your future assets instantly.',
    'header.subtitle.help': 'Contact Savora administrator or learn daily feature tutorials.',
    'btn.lang': 'Language: English',
    'btn.add_tx': 'Add Transaction',

    // Help.jsx
    'help.title': 'Savora Help Center',
    'help.desc': 'Quick guide on using Savora Finance app',
    'help.faq.title': 'FAQ (Frequently Asked Questions)',
    'help.guide.title': 'Savora Features Guide & Tutorials',
    'help.support.title': 'Contact Support Team',
    'help.support.desc': 'Need technical assistance or having issues?',
    'help.support.track': 'Track Ticket',
    'help.support.name': 'Full Name',
    'help.support.email': 'Active Email',
    'help.support.problem': 'Problem Description',
    'help.support.send': 'Send Support Ticket',
    'help.guide.ocr': 'Receipt Scan & OCR AI',
    'help.guide.read': 'Read',

    // Dashboard.jsx
    'dashboard.total_dana': 'Total Savora Funds',
    'dashboard.pemasukan': 'Income',
    'dashboard.pengeluaran': 'Expense',
    'dashboard.akun_saldo': 'Accounts & Balance',
    'dashboard.kelola_akun': 'Manage Accounts',
    'dashboard.kelola_kategori': 'Manage Categories',
    'dashboard.semua_rekening': 'All Accounts',
    'dashboard.transaksi_terakhir': 'Recent Transactions',
    'dashboard.aktivitas_terbaru': 'Your latest financial activities',
    'dashboard.lihat_semua': 'View All',

    // Settings.jsx
    'settings.title': 'Savora Settings',
    'settings.desc': 'Manage your preferences and data security.',
    'settings.cloud': 'Connectivity & Cloud System',
    'settings.uji': 'Test Supabase Connection',
    'settings.uji_desc': 'Ensure you are connected to the realtime database.',
    'settings.data': 'Data Management',
    'settings.arsip': 'Auto Archive Old Data',
    'settings.arsip_desc': 'Download old transaction history to Excel (CSV) and remove them from the database for a lighter and faster app.',
    'settings.reset': 'Total Database Reset (Factory Reset)',
    'settings.reset_desc': 'Restore all databases to default settings. Deletes all transaction histories, accounts, savings, and static UI.',

    // New strings for Backup/Restore/Profile
    'settings.profile': 'User Profile',
    'settings.profile_desc': 'Change your display name in the app.',
    'settings.profile_name_label': 'Display Name',
    'settings.profile_save': 'Save Profile',
    'settings.profile_save_success': 'Profile updated successfully!',
    'settings.backup_restore': 'Backup & Restore Data',
    'settings.backup_restore_desc': 'Copy or restore your data in JSON format. Unlike archiving, your data will not be deleted.',
    'settings.btn_backup': 'Copy Backup to Clipboard',
    'settings.backup_success': 'Data successfully copied to Clipboard!',
    'settings.backup_fail': 'Failed to create backup',
    'settings.restore_ph': 'Paste your JSON backup here...',
    'settings.btn_paste': 'Paste from Clipboard',
    'settings.btn_restore': 'Restore Data',
    'settings.restore_success': 'Data successfully restored!',
    'settings.restore_fail': 'Invalid or corrupted JSON format.',
    'settings.about_savora': 'About Savora AI',
    'settings.about_desc': 'Smart financial tracking app with AI integration (LLaMA 3) for your convenience.',
    'settings.about_version': 'Version 1.0.0 (AI Edition)',
    'settings.about_dev': 'Developed by You',

    // Transactions.jsx
    'tx.title': 'Complete Transaction History',
    'tx.subtitle': 'All tracking records of income and expenses',
    'tx.export': 'Export to CSV (Excel)',
    'tx.search_desc': 'Search Description',
    'tx.search_placeholder': 'Search...',
    'tx.type': 'Type',
    'tx.type_all': 'All Types',
    'tx.type_income': 'Income',
    'tx.type_expense': 'Expense',
    'tx.type_transfer': 'Cash Transfer',
    'tx.category': 'Category',
    'tx.category_all': 'All Categories',
    'tx.account': 'Account',
    'tx.account_all': 'All Accounts',
    'tx.sort': 'Sort By',
    'tx.sort_newest': 'Newest',
    'tx.sort_oldest': 'Oldest',
    'tx.sort_highest': 'Highest Amount',
    'tx.sort_lowest': 'Lowest Amount',
    'tx.col_date': 'Date',
    'tx.col_type': 'Type',
    'tx.col_category': 'Category',
    'tx.col_desc': 'Description / Notes',
    'tx.col_amount': 'Amount',
    'tx.col_action': 'Action',
    'tx.loading': 'Loading data...',
    'tx.not_found': 'No transaction data found.',
    'tx.delete_confirm': 'Are you sure you want to delete this transaction?',
    'tx.delete_success': 'Transaction deleted successfully!',
    'tx.delete_fail': 'Failed to delete: ',
    'tx.export_success': 'Successfully exported data to CSV',
    'tx.delete': 'Delete',

    // Savings.jsx
    'savings.delete_confirm': 'Are you sure you want to permanently delete this savings target?',
    'savings.delete_success': 'Savings target deleted successfully!',
    'savings.delete_fail': 'Failed to delete savings: ',
    'savings.title': 'Savora Savings Pocket',
    'savings.subtitle': 'Organize and allocate your savings funds neatly',
    'savings.filter_all': 'All',
    'savings.add_title': 'Create New Target',
    'savings.add_subtitle': 'Allocate a specific budget for your dreams',
    'savings.btn_deposit': 'Deposit',
    'savings.deadline': 'Deadline',
    'savings.schedule_auto': 'Auto',
    'savings.schedule_manual': 'Manual',

    // Debts.jsx
    'debts.load_fail': 'Failed to load debt and receivable data',
    'debts.add_success': 'Data added successfully',
    'debts.add_fail': 'Failed to add data: ',
    'debts.delete_confirm': 'Are you sure you want to delete this data?',
    'debts.delete_success': 'Data deleted successfully',
    'debts.delete_fail': 'Failed to delete data',
    'debts.pay_success': 'Payment recorded successfully',
    'debts.pay_fail': 'Failed to record payment',
    'debts.title': 'Debt & Receivable Records',
    'debts.subtitle': 'Monitor your obligations and receivables',
    'debts.btn_add': 'Add',
    'debts.tab_active': 'Active Records',
    'debts.tab_history': 'Payment History',
    'debts.empty_active_title': 'No records yet',
    'debts.empty_active_desc': 'Start recording a new debt or receivable',
    'debts.empty_history_title': 'No payment history yet',
    'debts.empty_history_desc': 'Debt/receivable payments will appear here',
    'debts.status_lunas': 'PAID',
    'debts.status_aktif': 'ACTIVE',
    'debts.no_desc': 'No description',
    'debts.total': 'Total:',
    'debts.paid': 'Paid:',
    'debts.remaining': 'Remaining:',
    'debts.btn_pay': 'Pay',
    'debts.history_pay_debt': 'Debt Payment:',
    'debts.history_pay_debt': 'Debt Payment:',
    'debts.history_pay_receive': 'Receivable Payment:',
    'debts.modal_add_title': 'New Record',
    'debts.modal_type': 'Type',
    'debts.type_debt': 'Debt (Payable)',
    'debts.type_receive': 'Receivable',
    'debts.modal_name': 'Party Name (Who?)',
    'debts.modal_name_ph': 'Example: John',
    'debts.modal_amount': 'Amount',
    'debts.modal_amount_ph': '50000',
    'debts.modal_desc': 'Description (Optional)',
    'debts.modal_desc_ph': 'Lunch money',
    'debts.modal_deadline': 'Deadline (Optional)',
    'debts.modal_btn_save': 'Save Record',
    'debts.modal_pay_title': 'Record Payment',
    'debts.modal_pay_for': 'Paying for:',
    'debts.modal_pay_remain': 'Remaining bill: ',
    'debts.modal_pay_amount': 'Payment Amount',
    'debts.modal_pay_acc': 'Select Cash Account',
    'debts.modal_pay_note_dec': 'This account balance will automatically decrease.',
    'debts.modal_pay_note_inc': 'This account balance will automatically increase.',
    'debts.modal_btn_pay': 'Save Payment',

    // Categories.jsx
    'cat.add_success': 'Category added successfully!',
    'cat.add_fail': 'Failed to save: ',
    'cat.delete_confirm': 'Delete this category?',
    'cat.delete_success': 'Category deleted successfully.',
    'cat.delete_fail': 'Failed to delete category: ',
    'cat.add_title': 'Add New Category',
    'cat.add_subtitle': 'Group your expenses as needed',
    'cat.label_name': 'Category Name',
    'cat.placeholder_name': 'e.g., Monthly Groceries',
    'cat.label_type': 'Category Type',
    'cat.label_limit': 'Monthly Budget Limit',
    'cat.label_optional': '(Optional)',
    'cat.placeholder_limit': 'e.g., 1500000',
    'cat.btn_save': 'Save Category',
    'cat.btn_saving': 'Saving...',
    'cat.list_title': 'Category List & Limit Control',
    'cat.list_subtitle': 'Set monthly spending limits to prevent overbudgeting.',
    'cat.col_name': 'Category Name',
    'cat.col_type': 'Type',
    'cat.col_limit': 'Budget Limit',
    'cat.col_action': 'Action',
    'cat.empty': 'No custom categories yet.',

    // Statistics.jsx
    'stat.tab_cashflow': 'Cashflow',
    'stat.tab_breakdown': 'Expense Breakdown',
    'stat.tab_assets': 'Asset Proportion',
    'stat.cf_title': 'Fund Flow Statistics',
    'stat.cf_subtitle': 'Visualization of cash inflows & outflows this month',
    'stat.cf_income': 'Income',
    'stat.cf_expense': 'Expense',
    'stat.loading_chart': 'Loading chart...',
    'stat.bd_title': 'Category Distribution',
    'stat.bd_total': 'Total Expense:',
    'stat.assets_title': 'Asset Allocation Proportion',
    'stat.assets_subtitle': 'Distribution of your total Savora funds in each active account',
    'stat.assets_empty': 'Asset balance is empty.',
    'stat.status_title': 'Active Account Status',
    'stat.status_monitored': 'Monitored Accounts',
    'stat.status_all': 'All Accounts',
    'stat.status_total': 'Total Funds',
    'stat.health_title': 'Savora Health Index',
    'stat.health_good': 'Good! Your cashflow is positive. Maintain it for a secure future.',
    'stat.health_bad': 'Caution! Your expenses exceed your assets. Review your daily budget immediately.',

    // Calendar.jsx
    'cal.save_fail': 'Failed to save note',
    'cal.month_income': 'This Month Income',
    'cal.month_expense': 'This Month Expense',
    'cal.month_net': 'Net Balance',
    'cal.sun': 'Sun',
    'cal.mon': 'Mon',
    'cal.tue': 'Tue',
    'cal.wed': 'Wed',
    'cal.thu': 'Thu',
    'cal.fri': 'Fri',
    'cal.sat': 'Sat',
    'cal.panel_title': 'Daily Activity',
    'cal.journal': 'Financial Journal',
    'cal.journal_ph': 'Write expense notes, ideas, or financial reflections today...',
    'cal.budget_limit': 'Daily Budget Limit',
    'cal.budget_limit_ph': 'Set spending limit...',
    'cal.usage': 'Usage',
    'cal.overbudget': 'Overbudget',
    'cal.safe': 'Safe',
    'cal.reminders': 'Reminders',
    'cal.reminder_ph': 'Add bill reminder...',
    'cal.tx_history': 'Daily Transaction History',
    'cal.tx_empty': 'No transactions',

    // AiAssistant.jsx
    'ai.consult_welcome': 'Hello! I am Savora AI. I can analyze your finances or provide investment recommendations and money-saving tips. Please type your question! (Example: "How to save on monthly groceries?")',
    'ai.catat_welcome': 'Instant Record Mode ready. Mention your transaction like "Buy coffee 50 thousand cash", and I will record it in your ledger.',
    'ai.clear_confirm': 'Clear chat history for this mode?',
    'ai.consult_cleared': 'Consultation chat history has been cleared.',
    'ai.catat_cleared': 'Instant record chat history has been cleared.',
    'ai.title': 'Savora Financial AI Advisor',
    'ai.status': 'Online & Ready to Answer',
    'ai.mode_consult': 'Consultation Mode',
    'ai.mode_catat': 'Instant Chat Mode',
    'ai.placeholder': 'Type your message here...',
    'ai.btn_send': 'Send',
    'ai.response_consult': '💡 Regarding your question "{msg}", Savora AI advises: Always track daily expenses and ensure they don\'t exceed 30% of this month\'s remaining salary. (Real AI system is currently being integrated)',
    'ai.response_catat_success': '✅ Success! I have recorded an {type} of {amount} for "{desc}" in the "{account}" wallet.{accMsg}',
    'ai.response_catat_fail': '❌ Failed to record transaction: {error}',
    'ai.response_catat_unknown': '❓ Sorry, I didn\'t catch that. Try a clearer format like: "Buy coffee 50k cash" or "Receive salary 5 million BCA".',
    'ai.acc_created': '\n(New wallet account "{account}" was automatically created).',

    // Notifications.jsx
    'notif.load_fail': 'Failed to load notifications',
    'notif.save_fail': 'Failed to save settings',
    'notif.limit_success': 'Balance limit saved successfully',
    'notif.limit_fail': 'Failed to save balance limit: ',
    'notif.clear_confirm': 'Clear all notification history?',
    'notif.clear_success': 'History cleared successfully',
    'notif.clear_fail': 'Failed to clear history',
    'notif.title': 'Financial Notification History',
    'notif.subtitle': 'Record of all security, budget limit, and bill activities of your account',
    'notif.filter_all': 'All',
    'notif.filter_unread': 'Unread',
    'notif.btn_clear': 'Clear History',
    'notif.empty': 'No notifications to display.',
    'notif.warn_title': 'Warning!',
    'notif.info_title': 'Information',
    'notif.btn_transfer': 'Transfer Funds',
    'notif.config_title': 'Reminder Configuration',
    'notif.config_subtitle': 'Adjust Savora warning limits',
    'notif.cfg_overbudget': 'Overbudget Warning',
    'notif.cfg_overbudget_desc': 'Notify when category expenses reach the budget limit',
    'notif.cfg_critical': 'Critical Balance Warning',
    'notif.cfg_critical_desc': 'Notify if your main account balance is running low',
    'notif.cfg_critical_min': 'Minimum Balance Limit',
    'notif.cfg_checklist': 'Bill Checklist Reminder',
    'notif.cfg_checklist_desc': 'Notify if there are pending daily agendas',
    'notif.msg_critical_desc': 'Your {account} account balance is now below the safe limit ({amount}).',
    'notif.msg_checklist_desc': 'You have {count} pending tasks/bills today.',
    'notif.msg_overbudget_desc': 'Expenses for category {category} this month ({spent}) have exceeded the limit ({limit}).',

    // Dashboard.jsx
    'dashboard.welcome': 'Welcome,',
    'dashboard.user_default': 'User',
    'dashboard.ocr_start': 'Starting receipt analysis with AI...',
    'dashboard.ocr_err_key': 'Groq API Key is not configured in Settings.',
    'dashboard.ocr_err_api': 'Failed to call Groq API',
    'dashboard.ocr_err_format': 'Invalid AI response format',
    'dashboard.ocr_success': 'Successfully read the receipt!',
    'dashboard.ocr_invalid': 'Could not find a valid amount on the receipt.',
    'dashboard.ocr_fail': 'Failed to process receipt: ',
    'dashboard.ocr_title': 'Savora AI Scan',
    'dashboard.ocr_subtitle': 'Take a photo of a shopping receipt to record it automatically.',
    'dashboard.ocr_title_loading': 'Analyzing Receipt...',
    'dashboard.ocr_subtitle_loading': 'Tesseract.js is processing the image...',
    'dashboard.btn_scan': 'Scan Receipt (OCR)',
    'dashboard.btn_scanning': 'Scanning...',
    'dashboard.tx_empty': 'No transaction activity yet.',

    // Settings - Additional
    'settings.del_confirm': 'Delete this wallet? All related transactions may lose their wallet reference.',
    'settings.del_success': 'Wallet deleted successfully.',
    'settings.del_fail': 'Failed to delete wallet: ',
    'settings.up_fail': 'Failed to update settings: ',
    'settings.pin_err': 'PIN must be 4 digits',
    'settings.pin_success': 'Security PIN saved successfully!',
    'settings.pin_fail': 'Failed to save PIN: ',
    'settings.groq_success': 'Groq API Key saved successfully!',
    'settings.groq_fail': 'Failed to save Groq API Key: ',
    'settings.reset_warn': 'CRITICAL WARNING: All your history, wallets, and savings data will be permanently deleted. Continue?',
    'settings.reset_success': 'Database has been factory reset!',
    'settings.reset_fail': 'Failed to reset database: ',
    'settings.archive_empty': 'System is optimal! No old transactions (over 30 days) to archive right now.',
    'settings.archive_success': 'Successfully archived and downloaded old transactions! Database is now lighter.',
    'settings.archive_fail': 'Failed to archive data: ',
    'settings.btn_connect_bank': 'Connect Bank Account',
    'settings.lbl_connected': 'Connected',
    'settings.btn_run_archive': 'Run Archive',
    'settings.btn_run_reset': 'Run Reset',
    'settings.lbl_fin_config': 'Financial Configuration',
    'settings.lbl_def_acc': 'Default Account',
    'settings.desc_def_acc': 'The primary account automatically selected when creating a new transaction.',
    'settings.lbl_acc_list': 'Accounts & Wallets List',
    'settings.desc_acc_list': 'Manage your wallets, bank accounts, or e-wallets.',
    'settings.btn_add_acc': 'Add Wallet',
    'settings.lbl_currency': 'Currency Format',
    'settings.desc_currency': 'Choose currency display format between Rupiah (IDR) or Dollar (USD).',
    'settings.lbl_security': 'Security & App Features',
    'settings.lbl_pin_lock': 'App PIN Lock',
    'settings.desc_pin_lock': 'Requires 4-digit PIN verification to open Savora.',
    'settings.lbl_change_pin': 'Change PIN Code',
    'settings.desc_change_pin': 'Change your 4-digit passcode for daily internal security protection.',
    'settings.lbl_ai_integ': 'AI Integration (Groq API Key)',
    'settings.desc_ai_integ': 'Enter your Groq API Key (gsk_...) to enable Savora AI Scan (OCR).',
    'settings.lbl_haptic': 'Haptic Feedback',
    'settings.desc_haptic': 'Enable subtle haptic vibration effects when pressing buttons.',
    'settings.btn_save': 'Save',
    'settings.select': '-- Select --',
    'settings.edit_wallet': 'Edit Wallet',
    'settings.del_wallet': 'Delete Wallet',

    // Help - Additional
    'help.faq.1.q': 'Is my data safe in Savora?',
    'help.faq.1.a': 'Very safe! All Savora transaction data is stored in a private cloud using Supabase Row Level Security.',
    'help.faq.2.q': 'What if I forget my security PIN?',
    'help.faq.2.a': 'You can reset your PIN through Settings, or clear app local data if fully locked out.',
    'help.guide.ai': 'Savora AI Chat Commands',
    'help.guide.savings': 'Savings Pocket Plan',
    'help.guide.limits': 'Budget Limits',
    'help.support.track_msg': 'Ticket tracking system (Zendesk) is under maintenance (MVP Simulation).',
    'help.support.send_msg': 'Support ticket sent! (Simulation)',
    'help.modal.ocr.title': 'Receipt Scan & OCR Guide',
    'help.modal.ocr.tag': 'SAVORA PREMIUM ACADEMY',
    'help.modal.ocr.desc': 'Savora AI Receipt Scan allows you to record physical expenses in seconds.',
    'help.modal.how_to': 'HOW TO USE:',
    'help.modal.ocr.step1': 'Click "Scan Receipt (OCR)" on the dashboard.',
    'help.modal.ocr.step2': 'Use a receipt image file.',
    'help.modal.ocr.step3': 'Savora AI will automatically extract the amount.',
    'help.modal.ocr.tips': 'Tips: Make sure the image is clear.',
    'help.modal.ai.title': 'Savora AI Chat Commands',
    'help.modal.ai.desc': 'Savora AI Chat is designed as your smart NLP financial assistant.',
    'help.modal.ai.step1': 'Open "Savora AI Chat" from the sidebar.',
    'help.modal.ai.step2': 'Type casually, e.g.: "Help me budget 5 million this month".',
    'help.modal.ai.step3': 'You can also record, e.g.: "I bought coffee 25k via GOPAY".',
    'help.modal.ai.tips': 'Tips: The more you ask, the better it recognizes your patterns.',
    'help.modal.savings.title': 'Savings Pocket Plan',
    'help.modal.savings.desc': 'The Savings Pocket feature helps allocate money away from daily expenses.',
    'help.modal.savings.step1': 'Open "Savings Target" and click Create Target.',
    'help.modal.savings.step2': 'Set Dream Name, Amount, and Deadline.',
    'help.modal.savings.step3': 'Transfer balance from Main Account to Savings Pocket.',
    'help.modal.savings.tips': 'Tips: Savings balance is hidden from Monthly Expenses chart.',
    'help.modal.limits.title': 'Budget Limits',
    'help.modal.limits.desc': 'Budget Limits act as your spending brakes.',
    'help.modal.limits.step1': 'Open "Categories & Limits".',
    'help.modal.limits.step2': 'Add category and set monthly limit.',
    'help.modal.limits.step3': 'When transactions break the limit, you get a notification alert.',
    'help.modal.limits.tips': 'Tips: Allocate 20% of income for savings first.',
    'help.modal.btn_understand': 'I Understand',
    'help.modal.btn_close': 'Close',
    'help.btn.ocr': 'Start Scan Now',
    'help.btn.ai': 'Start AI Chat',
    'help.btn.savings': 'Create Savings Goal',
    'help.btn.limits': 'Set Limit Now',

    // Modals
    'modal_tx.title_new': 'Record New Transaction',
    'modal_tx.type_label': 'Transaction Type',
    'modal_tx.income': 'Income',
    'modal_tx.expense': 'Expense',
    'modal_tx.saving': 'Savings',
    'modal_tx.transfer': 'Transfer',
    'modal_tx.amount_label': 'Amount',
    'modal_tx.amount_ph': 'Example: 50000',
    'modal_tx.category_label': 'Select Category',
    'modal_tx.category_other': 'Other',
    'modal_tx.desc_label': 'Description / Short Note',
    'modal_tx.desc_ph': 'Example: Lunch',
    'modal_tx.source_account': 'Source Account',
    'modal_tx.account': 'Account / Payment Method',
    'modal_tx.dest_account': 'Destination Account',
    'modal_tx.btn_saving': 'Saving...',
    'modal_tx.btn_save': 'Save Transaction Now',
    'modal_tx.success': 'Transaction saved successfully!',
    'modal_tx.fail': 'Failed to save transaction: ',

    'modal_acc.title_new': 'Add Wallet / Account',
    'modal_acc.name_label': 'Wallet Name (e.g. My Wallet)',
    'modal_acc.name_ph': 'Enter wallet name...',
    'modal_acc.type_label': 'Account Type',
    'modal_acc.type_cash': 'Cash',
    'modal_acc.type_bank': 'Bank Account',
    'modal_acc.type_ewallet': 'E-Wallet',
    'modal_acc.balance_label': 'Initial Balance (Optional)',
    'modal_acc.btn_saving': 'Saving...',
    'modal_acc.btn_save': 'Save Wallet',
    'modal_acc.success': 'Wallet added successfully!',
    'modal_acc.fail': 'Failed to add wallet: ',
    'modal_acc.title_edit': 'Edit Wallet',
    'modal_acc.name_new_label': 'New Wallet Name',
    'modal_acc.note': 'Note: Balance cannot be changed here. Please create an Adjustment Transaction.',
    'modal_acc.btn_save_edit': 'Save Changes',
    'modal_acc.success_edit': 'Wallet updated successfully!',
    'modal_acc.fail_edit': 'Failed to update wallet: ',

    'modal_sg.title': 'Create Saving Goal',
    'modal_sg.name_label': 'Goal Name',
    'modal_sg.name_ph': 'Example: Dream House DP, New Laptop',
    'modal_sg.amount_label': 'Target Amount',
    'modal_sg.amount_ph': 'Example: 15000000',
    'modal_sg.category_label': 'Saving Category (Pocket)',
    'modal_sg.cat_personal': 'Personal',
    'modal_sg.cat_mutual': 'Mutual',
    'modal_sg.cat_family': 'Family',
    'modal_sg.cat_custom': '+ Add Custom Category',
    'modal_sg.cat_custom_ph': 'New Category',
    'modal_sg.init_balance_label': 'Initial Saving',
    'modal_sg.deadline_label': 'Target Deadline',
    'modal_sg.schedule_label': 'Routine Deposit Schedule',
    'modal_sg.sch_manual': '🔄 Manual',
    'modal_sg.sch_first_day': '🌅 Every 1st of Month',
    'modal_sg.sch_last_day': '🌇 Every Month End',
    'modal_sg.sch_specific_date': '📅 Specific Date (Monthly)',
    'modal_sg.date_label': 'Monthly Deposit Date (1-28)',
    'modal_sg.date_ph': 'Example: 10',
    'modal_sg.btn_saving': 'Saving...',
    'modal_sg.btn_save': 'Save Target Goal',
    'modal_sg.success': 'Saving goal created successfully!',
    'modal_sg.fail': 'Failed to save saving goal: ',

    'modal_contrib.title': 'Deposit to Saving',
    'modal_contrib.target_lbl': 'Target:',
    'modal_contrib.amount_lbl': 'Deposit Amount',
    'modal_contrib.amount_ph': 'Example: 1000000',
    'modal_contrib.source_lbl': 'Select Funding Source',
    'modal_contrib.btn_saving': 'Depositing...',
    'modal_contrib.btn_save': 'Confirm Deposit',
    'modal_contrib.note': '*Auto-debit feature is currently under development in Savora.',
    'modal_contrib.success': 'Deposit to saving successful!',
    'modal_contrib.fail': 'Failed to deposit: ',
    'modal_contrib.insufficient_pt1': 'Balance in wallet ',
    'modal_contrib.insufficient_pt2': ' is insufficient (Remaining: Rp ',

    'modal_bank.title_select': 'Select Bank',
    'modal_bank.title_login': 'Login',
    'modal_bank.title_connect': 'Connecting...',
    'modal_bank.desc_select': 'Select the bank you want to connect with Savora (Open Banking API).',
    'modal_bank.desc_secure': 'Connection is secured with End-to-End encryption. Savora does not store your bank credentials.',
    'modal_bank.user_lbl': 'Username / User ID',
    'modal_bank.user_ph': 'Enter Bank User ID',
    'modal_bank.pass_lbl': 'Password / PIN',
    'modal_bank.pass_ph': '••••••••',
    'modal_bank.btn_back': 'Back',
    'modal_bank.btn_connect': 'Connect',
    'modal_bank.sync_title': 'Data Synchronization',
    'modal_bank.sync_desc_pt1': 'Connecting Savora with ',
    'modal_bank.sync_desc_pt2': ' via secure API...',
    'modal_bank.success_pt1': 'Successfully connected with ',
    'modal_bank.success_pt2': '! Account has been synchronized.',
    'modal_bank.fail': 'Failed to connect to ',

    'modal_notif.loading': 'Loading...',
    'modal_notif.empty': 'No active notifications.',
    'modal_notif.warn_title': 'Warning!',
    'modal_notif.info_title': 'Information',
    'modal_notif.title': 'Notification Center',
    'modal_notif.subtitle': 'Active Financial Alerts',
    'modal_notif.btn_all': 'View All & Configure',
    'modal_notif.btn_close': 'Close',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('id');

  useEffect(() => {
    const saved = localStorage.getItem('savora_lang');
    if (saved) setLang(saved);
  }, []);

  const toggleLanguage = () => {
    const next = lang === 'id' ? 'en' : 'id';
    setLang(next);
    localStorage.setItem('savora_lang', next);
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
